### ISSUE TITLE
add add add and more add

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/Ironforge#16]
https://github.com/ColonelKai/PSMPlugin/blob/master/src/main/java/colonelkai/psmplugin/modules/bordermaker/BorderMakerCommands.java

The set you have has a lot of adds, this can cause slowdowns, I built in something to avoid this. 

```java
return new BukkitCommandWrapper(
    new DeleteAnchorCommand(), 
    new FinalizeBorderCommand(),
    new InsertAnchorCommand(),
    new MoveAnchorCommand()
)
```

You can add as many as you like and then Java knows the size before it compiles so it wont have any slowdowns

**Comment by ColonelKai** [comment]
done
